In [14]:
a = [[(-0.04779334366321564, '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow'), (-3.194575309753418, '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁fallow'), (-6.3572163581848145, '▁that▁whereverver▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow'), (-8.80617618560791, '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follw'), (-10.710835456848145, '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follo')], [(-19.890230178833008, '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are'), (-19.961992263793945, '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁t▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are'), (-20.006446838378906, '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁in▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are'), (-20.091636657714844, '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁▁▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are'), (-20.118261337280273, '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁int▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are')], [(-22.587223052978516, '▁in▁spite▁of▁so▁long▁a▁discontinuation▁and▁this▁cpce▁said▁of▁many▁others▁they▁who▁in▁my▁storm▁have▁attempted▁to▁corrupt▁the▁manners▁of▁the▁world▁by▁new▁opinions'), (-22.587425231933594, '▁in▁spite▁of▁so▁long▁a▁discontinuation▁and▁this▁cpce▁said▁of▁many▁others▁they▁who▁in▁my▁story▁have▁attempted▁to▁corrupt▁the▁manners▁of▁the▁world▁by▁new▁opinions'), (-22.596145629882812, '▁in▁spite▁of▁so▁long▁a▁discontinuation▁and▁this▁ppce▁said▁of▁many▁others▁they▁who▁in▁my▁storm▁have▁attempted▁to▁corrupt▁the▁manners▁of▁the▁world▁by▁new▁opinions'), (-22.59634780883789, '▁in▁spite▁of▁so▁long▁a▁discontinuation▁and▁this▁ppce▁said▁of▁many▁others▁they▁who▁in▁my▁story▁have▁attempted▁to▁corrupt▁the▁manners▁of▁the▁world▁by▁new▁opinions'), (-22.674196243286133, '▁in▁spite▁of▁so▁long▁a▁discontinuation▁and▁this▁cps▁said▁of▁many▁others▁they▁who▁in▁my▁storm▁have▁attempted▁to▁corrupt▁the▁manners▁of▁the▁world▁by▁new▁opinions')], [(-19.5506591796875, '▁exclaimed▁ruth▁pulling▁helen▁by▁the▁sed▁we▁will▁leave▁the▁rch▁she▁drew▁her▁chum▁mos▁with▁her▁and▁they▁introduced▁themselves▁to▁the▁girls▁a▁the▁head▁of▁a▁oumn▁of▁freshness'), (-19.70145606994629, '▁exclaimed▁ruth▁pulling▁helen▁by▁the▁sed▁we▁will▁leave▁the▁rch▁she▁drew▁her▁chum▁los▁with▁her▁and▁they▁introduced▁themselves▁to▁the▁girls▁a▁the▁head▁of▁a▁oumn▁of▁freshness'), (-19.720430374145508, '▁exclaimed▁ruth▁pulling▁helen▁by▁the▁set▁we▁will▁leave▁the▁rch▁she▁drew▁her▁chum▁mos▁with▁her▁and▁they▁introduced▁themselves▁to▁the▁girls▁a▁the▁head▁of▁a▁oumn▁of▁freshness'), (-19.757522583007812, '▁exclaimed▁ruth▁pulling▁helen▁by▁the▁sed▁we▁will▁leave▁the▁march▁she▁drew▁her▁chum▁mos▁with▁her▁and▁they▁introduced▁themselves▁to▁the▁girls▁a▁the▁head▁of▁a▁oumn▁of▁freshness'), (-19.83285140991211, '▁exclaimed▁ruth▁pulling▁helen▁by▁the▁sed▁we▁will▁leave▁the▁rch▁she▁drew▁her▁chum▁mos▁with▁her▁and▁they▁introduced▁themselves▁to▁the▁girls▁at▁the▁head▁of▁a▁oumn▁of▁freshness')], [(-0.47973155975341797, '▁but▁it▁will▁be▁all▁right▁for▁you▁leslie▁you▁will▁go▁will▁you▁not'), (-1.5714359283447266, '▁but▁it▁will▁be▁all▁right▁to▁you▁leslie▁you▁will▁go▁will▁you▁not'), (-3.118943929672241, '▁but▁it▁will▁be▁all▁right▁for▁you▁leslie▁he▁will▁go▁will▁you▁not'), (-13.500043869018555, '▁but▁it▁will▁be▁all▁right▁for▁you▁leslie▁you▁will▁go▁will▁you▁not▁not'), (-14.541783332824707, '▁but▁it▁will▁be▁all▁right▁for▁you▁leslie▁you▁will▁go▁will▁you')], [(-16.81378173828125, "▁because▁if▁you▁were▁i▁have▁so▁wat▁to▁say▁to▁you▁and▁if▁not▁i'll▁go▁go▁then▁i▁cried▁besoaring▁he▁would▁obey▁too▁well▁and▁never▁come▁again▁i▁hastily▁added"), (-16.867183685302734, "▁because▁if▁you▁were▁i▁have▁so▁wt▁to▁say▁to▁you▁and▁if▁not▁i'll▁go▁go▁then▁i▁cried▁besoaring▁he▁would▁obey▁too▁well▁and▁never▁come▁again▁i▁hastily▁added"), (-16.916812896728516, "▁because▁if▁you▁were▁i▁have▁s▁wat▁to▁say▁to▁you▁and▁if▁not▁i'll▁go▁go▁then▁i▁cried▁besoaring▁he▁would▁obey▁too▁well▁and▁never▁come▁again▁i▁hastily▁added"), (-16.961400985717773, "▁because▁if▁you▁were▁i▁have▁sot▁to▁say▁to▁you▁and▁if▁not▁i'll▁go▁go▁then▁i▁cried▁besoaring▁he▁would▁obey▁too▁well▁and▁never▁come▁again▁i▁hastily▁added"), (-16.970243453979492, "▁because▁if▁you▁were▁i▁have▁s▁wt▁to▁say▁to▁you▁and▁if▁not▁i'll▁go▁go▁then▁i▁cried▁besoaring▁he▁would▁obey▁too▁well▁and▁never▁come▁again▁i▁hastily▁added")], [(-27.43811798095703, '▁but▁against▁the▁red▁ers▁and▁in▁most▁instances▁attempts▁to▁coerce▁the▁refractory▁and▁disobedient▁have▁been▁the▁signals▁of▁blud▁wars▁and▁one▁half▁of▁the▁confederate▁s▁displayed▁its▁banners▁against▁the▁other▁half'), (-27.525964736938477, '▁but▁against▁the▁red▁ders▁and▁in▁most▁instances▁attempts▁to▁coerce▁the▁refractory▁and▁disobedient▁have▁been▁the▁signals▁of▁blud▁wars▁and▁one▁half▁of▁the▁confederate▁s▁displayed▁its▁banners▁against▁the▁other▁half'), (-27.562610626220703, '▁but▁against▁the▁red▁ers▁and▁in▁most▁instances▁attempts▁to▁coerce▁the▁refractory▁and▁disobedient▁have▁been▁the▁signals▁of▁blud▁wars▁and▁one▁half▁of▁the▁confederate▁as▁displayed▁its▁banners▁against▁the▁other▁half'), (-27.577951431274414, '▁but▁against▁the▁red▁ers▁and▁in▁most▁instances▁attempts▁to▁coerce▁the▁refractory▁and▁disobedient▁have▁been▁the▁signals▁of▁blut▁wars▁and▁one▁half▁of▁the▁confederate▁s▁displayed▁its▁banners▁against▁the▁other▁half'), (-27.641202926635742, '▁but▁against▁the▁red▁ers▁and▁in▁most▁instances▁attempts▁to▁coerce▁the▁refractory▁and▁disobedient▁have▁been▁the▁signals▁of▁bluck▁wars▁and▁one▁half▁of▁the▁confederate▁s▁displayed▁its▁banners▁against▁the▁other▁half')], [(-22.935701370239258, '▁followed▁by▁his▁clerk▁lecoq▁rose▁and▁his▁fket▁well▁nigh▁with▁s▁anxiety▁toward▁the▁magistrate▁my▁research▁on▁the▁spot▁said▁the▁sactionary▁confirm▁me▁in▁the▁belief▁that▁you▁are▁right▁is▁there▁anything▁fresh▁yes▁sir'), (-22.94222640991211, '▁followed▁by▁his▁clerk▁lecoq▁rose▁and▁his▁fet▁well▁nigh▁with▁s▁anxiety▁toward▁the▁magistrate▁my▁research▁on▁the▁spot▁said▁the▁sactionary▁confirm▁me▁in▁the▁belief▁that▁you▁are▁right▁is▁there▁anything▁fresh▁yes▁sir'), (-23.003433227539062, '▁followed▁by▁his▁clerk▁lecoq▁rose▁and▁his▁fket▁well▁nigh▁with▁ps▁anxiety▁toward▁the▁magistrate▁my▁research▁on▁the▁spot▁said▁the▁sactionary▁confirm▁me▁in▁the▁belief▁that▁you▁are▁right▁is▁there▁anything▁fresh▁yes▁sir'), (-23.009958267211914, '▁followed▁by▁his▁clerk▁lecoq▁rose▁and▁his▁fet▁well▁nigh▁with▁ps▁anxiety▁toward▁the▁magistrate▁my▁research▁on▁the▁spot▁said▁the▁sactionary▁confirm▁me▁in▁the▁belief▁that▁you▁are▁right▁is▁there▁anything▁fresh▁yes▁sir'), (-23.036287307739258, '▁followed▁by▁his▁clerk▁lecoq▁rose▁and▁his▁ket▁well▁nigh▁with▁s▁anxiety▁toward▁the▁magistrate▁my▁research▁on▁the▁spot▁said▁the▁sactionary▁confirm▁me▁in▁the▁belief▁that▁you▁are▁right▁is▁there▁anything▁fresh▁yes▁sir')], [(-14.271989822387695, "▁you▁know▁you▁are▁never▁really▁bare▁in▁winter▁unless▁you▁have▁plenty▁to▁e▁that's▁so▁replied▁peter▁thoughtfully▁i▁never▁happened▁to▁think▁of▁it▁before▁just▁the▁same▁i▁don't▁see▁how▁you▁find▁food▁enough▁in▁the▁trees▁when▁they▁are▁all▁bare▁in▁winter"), (-14.446226119995117, "▁you▁know▁you▁are▁never▁really▁bare▁in▁winter▁unless▁you▁have▁plenty▁to▁e▁that's▁so▁replied▁peter▁thoughtfully▁i▁never▁happened▁to▁think▁of▁it▁before▁just▁the▁same▁don't▁see▁how▁you▁find▁food▁enough▁in▁the▁trees▁when▁they▁are▁all▁bare▁in▁winter"), (-14.916521072387695, "▁you▁know▁you▁are▁never▁really▁bare▁in▁winter▁unless▁you▁have▁plenty▁to▁e▁that's▁so▁replied▁peter▁thoughtfully▁i▁never▁happened▁to▁think▁of▁it▁before▁just▁the▁same▁i▁don't▁see▁how▁you▁find▁food▁enough▁in▁the▁trees▁andhen▁they▁are▁all▁bare▁in▁winter"), (-14.972944259643555, "▁you▁know▁you▁are▁never▁really▁bare▁in▁winter▁unless▁you▁have▁plenty▁to▁e▁that's▁so▁replied▁peter▁thoughtfully▁i▁never▁happened▁to▁think▁of▁it▁before▁just▁the▁same▁don't▁see▁how▁you▁find▁food▁enough▁in▁the▁trees▁andhen▁they▁are▁all▁bare▁in▁winter"), (-15.408866882324219, "▁you▁know▁you▁are▁never▁really▁bare▁in▁winter▁unless▁you▁have▁plenty▁to▁e▁that's▁so▁replied▁peter▁thoughtfully▁i▁never▁happened▁to▁think▁of▁it▁before▁just▁the▁same▁i▁don't▁see▁how▁you▁find▁food▁enough▁in▁the▁trees▁wh▁they▁are▁all▁bare▁in▁winter")], [(-35.20320510864258, '▁encouraged▁the▁saving▁appetites▁in▁him▁andt▁this▁countenancey▁unnecessary▁a▁ained▁amusement▁and▁ornament▁and▁then▁w▁ot▁into▁the▁company▁of▁a▁more▁refined▁licentious▁sort▁of▁people'), (-35.312496185302734, '▁encouraged▁the▁saving▁appetites▁in▁him▁andt▁this▁countenancey▁unnecessary▁a▁ained▁amusement▁and▁ornament▁no▁and▁then▁w▁ot▁into▁the▁company▁of▁a▁more▁refined▁licentious▁sort▁of▁people'), (-35.47099685668945, '▁encouraged▁the▁saving▁appetites▁in▁him▁andt▁this▁countenancey▁unnecessary▁a▁ain▁amusement▁and▁ornament▁and▁then▁w▁ot▁into▁the▁company▁of▁a▁more▁refined▁licentious▁sort▁of▁people'), (-35.48394012451172, '▁encouraged▁the▁saving▁appetites▁in▁him▁andt▁this▁countenancey▁unnecessary▁a▁amed▁amusement▁and▁ornament▁and▁then▁w▁ot▁into▁the▁company▁of▁a▁more▁refined▁licentious▁sort▁of▁people'), (-35.49028778076172, '▁encouraged▁the▁saving▁appetites▁in▁him▁andt▁this▁countenancey▁unnecessary▁a▁ained▁amusement▁and▁ornament▁and▁the▁w▁ot▁into▁the▁company▁of▁a▁more▁refined▁licentious▁sort▁of▁people')], [(-12.622674942016602, '▁when▁pressed▁by▁these▁facts▁and▁arguments▁to▁say▁that▁we▁transfors▁ourselves▁by▁the▁force▁of▁the▁imagination▁into▁disant▁ages▁and▁countries▁and▁consider▁the▁advantage▁which▁we▁should▁have▁reaped▁from▁these▁characters▁had▁wly▁been▁contemporaries▁and▁had▁any▁commerce▁with▁the▁persons'), (-12.727882385253906, '▁when▁pressed▁by▁these▁facts▁and▁arguments▁to▁say▁that▁we▁transforss▁ourselves▁by▁the▁force▁of▁the▁imagination▁into▁disant▁ages▁and▁countries▁and▁consider▁the▁advantage▁which▁we▁should▁have▁reaped▁from▁these▁characters▁had▁wly▁been▁contemporaries▁and▁had▁any▁commerce▁with▁the▁persons'), (-14.894627571105957, '▁when▁pressed▁by▁these▁facts▁and▁arguments▁to▁say▁that▁we▁transfors▁ourselves▁by▁the▁force▁of▁the▁imagination▁into▁disant▁ages▁and▁countries▁and▁consider▁the▁advantage▁which▁we▁should▁have▁reaped▁from▁these▁characters▁had▁we▁been▁contemporaries▁and▁had▁any▁commerce▁with▁the▁persons'), (-18.074764251708984, '▁when▁pressed▁by▁these▁facts▁and▁arguments▁to▁say▁that▁we▁transfors▁ourselves▁by▁the▁force▁of▁the▁imagination▁into▁disant▁ages▁and▁countries▁and▁consider▁the▁advantage▁which▁we▁should▁have▁reaped▁from▁these▁characters▁had▁wly▁been▁contemporaries▁and▁had▁any▁commerce▁with▁the▁persones'), (-18.179973602294922, '▁when▁pressed▁by▁these▁facts▁and▁arguments▁to▁say▁that▁we▁transforss▁ourselves▁by▁the▁force▁of▁the▁imagination▁into▁disant▁ages▁and▁countries▁and▁consider▁the▁advantage▁which▁we▁should▁have▁reaped▁from▁these▁characters▁had▁wly▁been▁contemporaries▁and▁had▁any▁commerce▁with▁the▁persones')], [(-18.834009170532227, '▁i▁ma▁you▁understand▁therefore▁in▁the▁absence▁of▁the▁gearness▁of▁your▁shame▁for▁i▁do▁not▁wish▁to▁humiliate▁you▁that▁you▁are▁from▁this▁moment▁at▁perfect▁liberty▁to▁leave▁and▁that▁you▁may▁in▁return▁to▁your▁mother▁at▁blois▁la▁valliere▁could▁not▁sink'), (-18.85610008239746, '▁i▁ma▁you▁understand▁therefore▁in▁the▁absence▁of▁the▁gearness▁of▁your▁shame▁for▁i▁do▁not▁wish▁to▁humiliate▁you▁that▁you▁are▁from▁this▁moment▁at▁perfect▁liberty▁to▁leave▁and▁that▁you▁may▁return▁to▁your▁mother▁at▁blois▁la▁valliere▁could▁not▁sink'), (-18.995595932006836, '▁i▁c▁you▁understand▁therefore▁in▁the▁absence▁of▁the▁gearness▁of▁your▁shame▁for▁i▁do▁not▁wish▁to▁humiliate▁you▁that▁you▁are▁from▁this▁moment▁at▁perfect▁liberty▁to▁leave▁and▁that▁you▁may▁in▁return▁to▁your▁mother▁at▁blois▁la▁valliere▁could▁not▁sink'), (-19.013280868530273, '▁i▁mak▁you▁understand▁therefore▁in▁the▁absence▁of▁the▁gearness▁of▁your▁shame▁for▁i▁do▁not▁wish▁to▁humiliate▁you▁that▁you▁are▁from▁this▁moment▁at▁perfect▁liberty▁to▁leave▁and▁that▁you▁may▁in▁return▁to▁your▁mother▁at▁blois▁la▁valliere▁could▁not▁sink'), (-19.01768684387207, '▁i▁c▁you▁understand▁therefore▁in▁the▁absence▁of▁the▁gearness▁of▁your▁shame▁for▁i▁do▁not▁wish▁to▁humiliate▁you▁that▁you▁are▁from▁this▁moment▁at▁perfect▁liberty▁to▁leave▁and▁that▁you▁may▁return▁to▁your▁mother▁at▁blois▁la▁valliere▁could▁not▁sink')], [(-33.733394622802734, '▁at▁last▁he▁reflected▁how▁she▁had▁just▁stripped▁herself▁and▁how▁in▁the▁morning▁she▁should▁cmmanced▁being▁dressed▁and▁he▁thought▁perhaps▁he▁was▁too▁strict▁with▁her▁and▁if▁he▁left▁her▁his▁own▁way▁they▁could▁manage▁to▁be▁happy▁sometiwgether▁even▁i▁she▁did▁before'), (-33.8335075378418, '▁at▁last▁he▁reflected▁how▁she▁had▁just▁stripped▁herself▁and▁how▁in▁the▁morning▁she▁should▁cmmanced▁being▁dressed▁and▁he▁thought▁perhaps▁he▁was▁too▁strict▁with▁her▁and▁if▁he▁left▁her▁his▁own▁way▁they▁could▁manage▁to▁be▁happy▁sometiwgether▁even▁i▁he▁did▁before'), (-33.91394805908203, '▁at▁last▁he▁reflected▁how▁she▁had▁just▁stripped▁herself▁and▁how▁in▁the▁morning▁she▁should▁cmmanced▁being▁dressed▁and▁he▁thought▁perhaps▁he▁was▁too▁strict▁with▁her▁and▁if▁he▁left▁her▁his▁own▁way▁they▁could▁manage▁to▁be▁happy▁sometimgether▁even▁i▁she▁did▁before'), (-33.99868392944336, '▁at▁last▁he▁reflected▁how▁she▁had▁just▁stripped▁herself▁and▁how▁in▁the▁morning▁she▁should▁cmmanced▁being▁dressed▁and▁he▁thought▁perhaps▁he▁was▁too▁strict▁with▁her▁and▁if▁he▁left▁her▁his▁own▁way▁they▁could▁manage▁to▁be▁happy▁sometiwgether▁even▁i▁did▁before'), (-34.014060974121094, '▁at▁last▁he▁reflected▁how▁she▁had▁just▁stripped▁herself▁and▁how▁in▁the▁morning▁she▁should▁cmmanced▁being▁dressed▁and▁he▁thought▁perhaps▁he▁was▁too▁strict▁with▁her▁and▁if▁he▁left▁her▁his▁own▁way▁they▁could▁manage▁to▁be▁happy▁sometimgether▁even▁i▁he▁did▁before')], [(-24.00459861755371, '▁in▁eighteen▁forty▁five▁there▁died▁at▁buxton▁at▁the▁age▁of▁ninety▁six▁a▁woman▁named▁pheasy▁mon▁who▁had▁been▁for▁many▁years▁an▁inveterterat▁bulker▁her▁death▁was▁caused▁by▁the▁accidental▁ignition▁of▁her▁clothes▁as▁she▁was▁suting▁her▁pipe▁at▁the▁fire'), (-24.12700080871582, '▁in▁eighteen▁forty▁five▁there▁died▁at▁buxton▁at▁the▁age▁of▁ninety▁six▁a▁woman▁named▁pheasy▁mon▁who▁had▁been▁for▁many▁years▁an▁inveterterab▁bulker▁her▁death▁was▁caused▁by▁the▁accidental▁ignition▁of▁her▁clothes▁as▁she▁was▁suting▁her▁pipe▁at▁the▁fire'), (-24.356056213378906, '▁in▁eighteen▁forty▁five▁there▁died▁at▁buxton▁at▁the▁age▁of▁ninety▁six▁a▁woman▁named▁pheasy▁mon▁who▁had▁been▁for▁many▁years▁an▁inveterterat▁bulker▁her▁death▁was▁caused▁by▁the▁accidental▁ignition▁of▁her▁clothes▁as▁she▁was▁suting▁her▁pipe▁at▁the▁fier'), (-24.478458404541016, '▁in▁eighteen▁forty▁five▁there▁died▁at▁buxton▁at▁the▁age▁of▁ninety▁six▁a▁woman▁named▁pheasy▁mon▁who▁had▁been▁for▁many▁years▁an▁inveterterab▁bulker▁her▁death▁was▁caused▁by▁the▁accidental▁ignition▁of▁her▁clothes▁as▁she▁was▁suting▁her▁pipe▁at▁the▁fier'), (-24.554155349731445, '▁in▁eighteen▁forty▁five▁there▁died▁at▁buxton▁at▁the▁age▁of▁ninety▁six▁a▁woman▁named▁pheasy▁mon▁who▁had▁been▁for▁many▁years▁an▁inveterterat▁bulker▁her▁death▁was▁caused▁by▁the▁accidental▁ignition▁of▁her▁clothes▁as▁she▁was▁suting▁her▁pipe▁at▁the▁cire')], [(-13.91437816619873, "▁said▁eugene▁when▁they▁were▁standing▁under▁the▁bank▁roared▁and▁riven▁at▁b▁the▁wind▁there's▁the▁light▁of▁her▁fire▁i'll▁take▁her▁bockugh▁the▁window"), (-13.934626579284668, "▁said▁eugene▁when▁they▁were▁standing▁under▁the▁bank▁roared▁and▁riven▁at▁b▁the▁wind▁there's▁the▁light▁of▁her▁fire▁i'll▁take▁her▁loockugh▁the▁window"), (-13.953266143798828, "▁said▁eugene▁when▁they▁were▁standing▁under▁the▁bank▁roared▁and▁riven▁at▁b▁the▁wind▁there's▁the▁light▁of▁her▁fire▁i'll▁take▁you▁bockugh▁the▁window"), (-13.973515510559082, "▁said▁eugene▁when▁they▁were▁standing▁under▁the▁bank▁roared▁and▁riven▁at▁b▁the▁wind▁there's▁the▁light▁of▁her▁fire▁i'll▁take▁you▁loockugh▁the▁window"), (-14.115560531616211, "▁said▁eugene▁when▁they▁were▁standing▁under▁the▁bank▁roared▁and▁riven▁at▁b▁the▁wind▁theere's▁the▁light▁of▁her▁fire▁i'll▁take▁her▁bockugh▁the▁window")], [(-0.00046899920562282205, '▁hastened▁to▁meet▁him▁at▁the▁appointed▁place▁of▁execution'), (-8.499403953552246, '▁hastened▁to▁meet▁him▁a▁the▁appointed▁place▁of▁execution'), (-10.963702201843262, '▁hastened▁to▁meet▁him▁at▁the▁appointed▁place▁of▁exeecution'), (-11.027192115783691, '▁hastened▁to▁meet▁him▁at▁the▁appointed▁place▁of▁execution▁and'), (-16.14539909362793, '▁hastened▁to▁meet▁him▁at▁the▁appointed▁place▁of▁executioner')]]

In [15]:
a[0][1]

a[0][0][1]


'▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow'

In [16]:
import numpy as np
a = np.array(a)

a

array([[['-0.04779334366321564',
         '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow'],
        ['-3.194575309753418',
         '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁fallow'],
        ['-6.3572163581848145',
         '▁that▁whereverver▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow'],
        ['-8.80617618560791',
         '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follw'],
        ['-10.710835456848145',
         '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follo']],

       [['-19.890230178833008',
         '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are'],
        ['-19.961992263793945',
         '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomp

In [98]:
b = a[..., 1]

b

array([['▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow',
        '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁fallow',
        '▁that▁whereverver▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow',
        '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follw',
        '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follo'],
       ['▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are',
        '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁t▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are',
        '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁force

In [100]:
b = b.reshape(-1)
b

array(['▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow',
       '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁fallow',
       '▁that▁whereverver▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follow',
       '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follw',
       '▁that▁wherever▁i▁could▁enter▁my▁head▁my▁whole▁body▁might▁follo',
       '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are',
       '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accomplished▁the▁bayn▁liwe▁in▁t▁eleven▁the▁victory▁is▁highly▁instructive▁as▁great▁victories▁usually▁are',
       '▁the▁coalition▁of▁sportsmen▁zoologists▁and▁friends▁of▁wild▁life▁in▁general▁proved▁irresistible▁just▁as▁a▁similar▁union▁of▁forces▁accompl

In [13]:
d = [[60, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31], [60, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31], [60, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31], [60, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 15, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31], [36, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31], [3, 79, 13, 12, 32, 78, 7, 9, 3, 67, 19, 44, 12, 9, 5, 13, 69, 7, 47, 41, 30, 6, 47, 8, 30, 5, 17, 58, 69, 1, 47, 106, 59, 59, 37, 52, 9, 70, 4, 82, 3, 13, 61, 4, 27, 5, 85, 43, 79, 47, 117, 22, 45, 1, 4, 64, 6, 2, 1, 3, 11, 2, 41, 32, 43, 29, 6, 2, 2, 7, 48, 55, 30, 39, 8, 60, 97, 77, 19, 46, 9, 62, 111, 51, 50, 14, 18, 91, 12, 9, 5, 13, 12, 9, 5, 13, 2, 16, 17, 6, 33, 1], [41, 79, 13, 12, 32, 78, 7, 9, 3, 67, 19, 44, 12, 9, 5, 13, 69, 7, 47, 41, 30, 6, 47, 8, 30, 5, 17, 58, 69, 1, 47, 106, 59, 59, 37, 52, 9, 70, 4, 82, 3, 13, 61, 4, 27, 5, 85, 43, 79, 47, 117, 22, 45, 1, 4, 64, 6, 2, 1, 3, 11, 2, 41, 32, 43, 29, 6, 2, 2, 7, 48, 55, 30, 39, 8, 60, 97, 77, 19, 46, 9, 62, 111, 51, 50, 14, 18, 91, 12, 9, 5, 13, 12, 9, 5, 13, 2, 16, 17, 6, 33, 1], [3, 79, 13, 12, 32, 78, 85, 3, 67, 19, 44, 12, 9, 5, 13, 69, 7, 47, 41, 30, 6, 47, 8, 30, 5, 17, 58, 69, 1, 47, 106, 59, 59, 37, 52, 9, 70, 4, 82, 3, 13, 61, 4, 27, 5, 85, 43, 79, 47, 117, 22, 45, 1, 4, 64, 6, 2, 1, 3, 11, 2, 41, 32, 43, 29, 6, 2, 2, 7, 48, 55, 30, 39, 8, 60, 97, 77, 19, 46, 9, 62, 111, 51, 50, 14, 18, 91, 12, 9, 5, 13, 12, 9, 5, 13, 2, 16, 17, 6, 33, 1], [41, 79, 13, 12, 32, 78, 85, 3, 67, 19, 44, 12, 9, 5, 13, 69, 7, 47, 41, 30, 6, 47, 8, 30, 5, 17, 58, 69, 1, 47, 106, 59, 59, 37, 52, 9, 70, 4, 82, 3, 13, 61, 4, 27, 5, 85, 43, 79, 47, 117, 22, 45, 1, 4, 64, 6, 2, 1, 3, 11, 2, 41, 32, 43, 29, 6, 2, 2, 7, 48, 55, 30, 39, 8, 60, 97, 77, 19, 46, 9, 62, 111, 51, 50, 14, 18, 91, 12, 9, 5, 13, 12, 9, 5, 13, 2, 16, 17, 6, 33, 1], [3, 79, 13, 32, 78, 7, 9, 3, 67, 19, 44, 12, 9, 5, 13, 69, 7, 47, 41, 30, 6, 47, 8, 30, 5, 17, 58, 69, 1, 47, 106, 59, 59, 37, 52, 9, 70, 4, 82, 3, 13, 61, 4, 27, 5, 85, 43, 79, 47, 117, 22, 45, 1, 4, 64, 6, 2, 1, 3, 11, 2, 41, 32, 43, 29, 6, 2, 2, 7, 48, 55, 30, 39, 8, 60, 97, 77, 19, 46, 9, 62, 111, 51, 50, 14, 18, 91, 12, 9, 5, 13, 12, 9, 5, 13, 2, 16, 17, 6, 33, 1], [113, 81, 37, 52, 2, 77, 56, 7, 65, 9, 20, 77, 4, 57, 11, 18, 8, 2, 1, 125, 17, 4, 5, 92, 2, 83, 90, 120, 15, 68, 29, 44, 5, 2, 57, 1, 20, 8, 11, 29, 50, 56, 18, 18, 22, 77, 10, 5, 4, 1, 8, 29, 34, 4, 7, 19, 15, 10, 34, 2, 23, 8, 81, 35, 82, 54, 7, 1, 25, 83, 8, 77, 2, 15, 10, 4, 23, 119, 43, 69, 24, 61, 4, 18, 43, 93, 45, 6, 77, 5, 2, 52, 22, 49, 16, 5, 4, 7, 2, 32, 7, 18], [113, 81, 37, 52, 2, 77, 56, 7, 65, 9, 20, 77, 4, 57, 11, 18, 8, 2, 1, 125, 17, 4, 5, 92, 2, 83, 90, 120, 15, 68, 29, 44, 5, 2, 57, 1, 20, 8, 11, 29, 50, 56, 18, 18, 22, 77, 10, 5, 4, 1, 8, 29, 34, 4, 7, 19, 15, 10, 34, 2, 23, 8, 81, 35, 82, 54, 7, 1, 25, 83, 8, 77, 2, 15, 10, 4, 23, 119, 43, 69, 24, 61, 4, 18, 43, 93, 45, 6, 9, 77, 5, 2, 52, 22, 49, 16, 5, 4, 7, 2, 32, 7, 18], [113, 81, 37, 52, 2, 77, 56, 7, 65, 9, 20, 77, 4, 57, 11, 18, 8, 2, 1, 125, 17, 4, 5, 92, 2, 83, 90, 120, 15, 68, 29, 44, 5, 2, 57, 1, 20, 8, 11, 29, 50, 56, 18, 18, 22, 77, 10, 5, 4, 1, 8, 29, 34, 4, 7, 19, 15, 10, 34, 2, 23, 8, 81, 35, 82, 54, 7, 1, 25, 83, 8, 77, 2, 15, 10, 4, 23, 119, 43, 69, 24, 61, 4, 18, 43, 93, 45, 77, 5, 2, 52, 22, 49, 16, 5, 4, 7, 2, 32, 7, 18], [113, 81, 37, 52, 2, 77, 56, 7, 65, 9, 20, 77, 4, 57, 11, 18, 8, 2, 1, 125, 17, 85, 5, 92, 2, 83, 90, 120, 15, 68, 29, 44, 5, 2, 57, 1, 20, 8, 11, 29, 50, 56, 18, 18, 22, 77, 10, 5, 4, 1, 8, 29, 34, 4, 7, 19, 15, 10, 34, 2, 23, 8, 81, 35, 82, 54, 7, 1, 25, 83, 8, 77, 2, 15, 10, 4, 23, 119, 43, 69, 24, 61, 4, 18, 43, 93, 45, 6, 77, 5, 2, 52, 22, 49, 16, 5, 4, 7, 2, 32, 7, 18], [113, 81, 37, 52, 2, 77, 56, 7, 65, 9, 20, 77, 4, 57, 11, 18, 8, 2, 1, 125, 17, 4, 5, 92, 2, 83, 90, 120, 15, 68, 29, 44, 5, 2, 57, 1, 20, 8, 11, 29, 50, 56, 18, 18, 22, 77, 10, 5, 4, 1, 8, 29, 34, 4, 7, 19, 15, 10, 34, 2, 23, 8, 81, 35, 82, 54, 7, 1, 25, 83, 8, 77, 2, 15, 10, 4, 23, 119, 43, 69, 24, 61, 4, 18, 43, 93, 95, 6, 77, 5, 2, 52, 22, 49, 16, 5, 4, 7, 2, 32, 7, 18], [90, 35, 8, 3, 34, 38, 75, 40, 1, 98, 41, 3, 14, 46, 33, 100, 3, 33, 11, 6, 25, 2, 12, 47, 12, 48, 6, 15, 4, 88, 3, 46, 3, 42, 6, 110, 20, 41, 32, 100, 93, 49, 42, 35, 8, 77, 51, 5, 57, 39, 4, 12, 4, 53, 40, 14, 35, 8, 90, 65, 11, 26, 100, 30, 6, 15, 10, 9, 117, 96, 11, 1, 76, 88, 27, 28, 5, 4, 100, 53, 7, 9, 41, 93, 77, 5, 2, 52, 22, 64, 40, 33, 59, 100, 27, 6, 15, 10, 9, 49, 8, 21, 27, 28, 42, 41, 37, 6, 10, 4, 18, 35, 22, 45, 1, 4, 60, 15, 4, 23, 12, 36, 7, 56], [90, 35, 8, 3, 34, 38, 75, 40, 1, 98, 41, 3, 14, 46, 33, 100, 3, 33, 11, 6, 25, 2, 12, 47, 12, 48, 6, 15, 4, 88, 3, 46, 3, 42, 6, 110, 20, 41, 32, 100, 93, 49, 42, 35, 8, 77, 51, 5, 57, 39, 4, 12, 4, 53, 40, 11, 35, 8, 90, 65, 11, 26, 100, 30, 6, 15, 10, 9, 117, 96, 11, 1, 76, 88, 27, 28, 5, 4, 100, 53, 7, 9, 41, 93, 77, 5, 2, 52, 22, 64, 40, 33, 59, 100, 27, 6, 15, 10, 9, 49, 8, 21, 27, 28, 42, 41, 37, 6, 10, 4, 18, 35, 22, 45, 1, 4, 60, 15, 4, 23, 12, 36, 7, 56], [90, 35, 8, 3, 34, 38, 75, 40, 1, 98, 41, 35, 3, 14, 46, 33, 100, 3, 33, 11, 6, 25, 2, 12, 47, 12, 48, 6, 15, 4, 88, 3, 46, 3, 42, 6, 110, 20, 41, 32, 100, 93, 49, 42, 35, 8, 77, 51, 5, 57, 39, 4, 12, 4, 53, 40, 14, 35, 8, 90, 65, 11, 26, 100, 30, 6, 15, 10, 9, 117, 96, 11, 1, 76, 88, 27, 28, 5, 4, 100, 53, 7, 9, 41, 93, 77, 5, 2, 52, 22, 64, 40, 33, 59, 100, 27, 6, 15, 10, 9, 49, 8, 21, 27, 28, 42, 41, 37, 6, 10, 4, 18, 35, 22, 45, 1, 4, 60, 15, 4, 23, 12, 36, 7, 56], [90, 35, 8, 3, 34, 38, 75, 40, 1, 98, 41, 3, 14, 46, 33, 100, 3, 33, 11, 6, 25, 2, 12, 47, 12, 48, 6, 15, 4, 88, 3, 46, 3, 42, 6, 110, 20, 41, 32, 100, 93, 49, 42, 35, 8, 77, 51, 5, 57, 39, 4, 12, 4, 53, 40, 14, 35, 8, 90, 65, 11, 26, 100, 30, 6, 15, 10, 9, 117, 96, 11, 1, 76, 88, 27, 28, 5, 4, 100, 53, 7, 9, 41, 93, 77, 5, 2, 52, 22, 64, 40, 33, 59, 100, 27, 6, 15, 10, 9, 49, 8, 21, 27, 28, 42, 41, 37, 6, 10, 4, 18, 35, 22, 45, 1, 4, 60, 15, 4, 23, 12, 36, 5, 56], [90, 35, 8, 3, 34, 38, 75, 40, 1, 98, 41, 3, 14, 46, 33, 100, 3, 33, 11, 6, 25, 2, 12, 47, 12, 48, 6, 15, 4, 88, 3, 46, 3, 42, 6, 110, 20, 41, 32, 100, 93, 49, 42, 35, 8, 77, 51, 5, 57, 39, 4, 12, 4, 53, 40, 11, 35, 8, 90, 65, 11, 26, 100, 30, 6, 15, 10, 9, 117, 96, 11, 1, 76, 88, 27, 28, 5, 4, 100, 53, 7, 9, 41, 93, 77, 5, 2, 52, 22, 64, 40, 33, 59, 100, 27, 6, 15, 10, 9, 49, 8, 21, 27, 28, 42, 41, 37, 6, 10, 4, 18, 35, 22, 45, 1, 4, 60, 15, 4, 23, 12, 36, 5, 56]]

In [14]:
import numpy as np
# zero padding to make the element of d same length
def get_numpy_from_nonfixed_2d_array(aa, fixed_length, padding_value=0):
    rows = []
    for a in aa:
        rows.append(np.pad(a, (0, fixed_length), 'constant', constant_values=padding_value)[:fixed_length])
    return np.concatenate(rows, axis=0).reshape(-1, fixed_length)

# get the max length of the element of d
for a in d:
    print(a)
    print(len(a))
max_length = max([len(a) for a in d])
print(max_length)
# get the numpy array
np_array = get_numpy_from_nonfixed_2d_array(d, max_length)

[60, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31]
55
[60, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31]
56
[60, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31]
56
[60, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 15, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52, 31, 73, 80, 76, 13, 31, 95, 48, 44, 29, 34, 4, 11, 31]
55
[36, 6, 12, 19, 56, 17, 4, 18, 8, 36, 24, 9, 7, 85, 14, 20, 3, 15, 10, 4, 7, 13, 5, 4, 1, 55, 49, 19, 5, 13, 1, 107, 107, 11, 15, 68, 29, 7, 2, 28, 7, 52

In [12]:
np_array[0]

array([ 60,  12,  19,  56,  17,   4,  18,   8,  36,  24,   9,   7,  85,
        14,  20,   3,  15,  10,   4,   7,  13,   5,   4,   1,  55,  49,
        19,   5,  13,   1, 107, 107,  11,  15,  68,  29,   7,   2,  28,
         7,  52,  31,  73,  80,  76,  13,  31,  95,  48,  44,  29,  34,
         4,  11,  31,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0])

In [140]:
import torch
log_probs_st = torch.rand(2, 3, 4)
print(log_probs_st)
log_probs_st = log_probs_st.repeat(1,2,1).reshape(2*2, 3, 4)
print(log_probs_st)

tensor([[[0.0071, 0.9600, 0.0642, 0.7396],
         [0.5623, 0.3321, 0.0967, 0.0048],
         [0.1052, 0.9329, 0.5303, 0.0520]],

        [[0.8876, 0.8374, 0.3522, 0.2198],
         [0.5722, 0.5977, 0.2045, 0.0587],
         [0.2904, 0.6445, 0.1375, 0.0183]]])
tensor([[[0.0071, 0.9600, 0.0642, 0.7396],
         [0.5623, 0.3321, 0.0967, 0.0048],
         [0.1052, 0.9329, 0.5303, 0.0520]],

        [[0.0071, 0.9600, 0.0642, 0.7396],
         [0.5623, 0.3321, 0.0967, 0.0048],
         [0.1052, 0.9329, 0.5303, 0.0520]],

        [[0.8876, 0.8374, 0.3522, 0.2198],
         [0.5722, 0.5977, 0.2045, 0.0587],
         [0.2904, 0.6445, 0.1375, 0.0183]],

        [[0.8876, 0.8374, 0.3522, 0.2198],
         [0.5722, 0.5977, 0.2045, 0.0587],
         [0.2904, 0.6445, 0.1375, 0.0183]]])


In [21]:
import torch
a = torch.rand(2,3)

b = a.shape[1]
c = torch.Tensor([b] * 5)

c

tensor([3., 3., 3., 3., 3.])

In [4]:
import torch
a= torch.tensor([1495.3379, 1497.0336, 1496.6765, 1496.4739, 1498.3593, 1260.3821,
        1260.2163, 1262.2144, 1260.8037, 1261.8066, 1271.8314, 1272.4495,
        1272.2683, 1272.8861, 1273.7302,  283.8343,  283.5350,  279.0444,
         284.1452,  281.2862])
b = torch.tensor([1.2649, 1.2501, 1.2036, 1.1977, 1.1925, 1.2329, 1.2240, 1.2218, 1.2152,
        1.2133, 1.2379, 1.2295, 1.2250, 1.2171, 1.1979, 2.6023, 1.0413, 1.0031,
        1.0000, 1.0000])

c = a * b
c

tensor([1891.4529, 1871.4417, 1801.3999, 1792.3268, 1786.7935, 1553.9250,
        1542.5048, 1542.1735, 1532.1287, 1530.9500, 1574.4001, 1564.4767,
        1558.5287, 1549.2297, 1525.8015,  738.6219,  295.2450,  279.9095,
         284.1452,  281.2862])

In [90]:
a = torch.Tensor([[[1,2,3,4,5,6], 
                   [4,5,6,1,2,3], 
                   [0,0,0,0,0,0]],
                  [[1,2,3,4,5,6], 
                   [4,5,2,3,1,8], 
                   [3,1,7,3,2,1]]])


# Make the largest element in each row to be 1 and the rest to be 0
a = torch.nn.functional.one_hot(a.argmax(dim=2))

print(a)


a[:, :, 2] = 0
a[:, :, 0] = 0

a.shape # shape (B, T, 129)
    

tensor([[[0, 0, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 0],
         [1, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 1],
         [0, 0, 1, 0, 0, 0]]])


torch.Size([2, 3, 6])

In [87]:
b = torch.Tensor([[[2,2,2,2,2,2], 
                   [3,3,3,3,3,3], 
                   [2,2,2,2,2,2]],
                  [[2,2,2,2,2,2], 
                   [-1,-1,-1,-1,-1,-1], 
                   [5,5,5,5,5,5]]])

c = b * a
print(c)
d = torch.sum(c)
print(d)

tensor([[[ 0.,  0.,  0.,  0.,  0.,  2.],
         [ 0.,  0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.,  2.],
         [-0., -0., -0., -0., -0., -1.],
         [ 0.,  0.,  0.,  0.,  0.,  0.]]])
tensor(3.)
