In [42]:
import torch

blank_ = 128
alphabet_size = 129


for i in range(645):
    if (i - blank_) % alphabet_size == 0:
        d = int((i - blank_) / alphabet_size)
        print(i, ',', d)

128 , 0
257 , 1
386 , 2
515 , 3
644 , 4


In [58]:
import torch

blank_ = 128
alphabet_size = 129


for i in range(645):
    if (i - 0) % alphabet_size == 0:
        d = int((i - 0) / alphabet_size)
        print(i, ',', d)

0 , 0
129 , 1
258 , 2
387 , 3
516 , 4


In [16]:
T = 100
for t in range(T, 0, -1):
    for i in range(645):
        if (i - blank_) % alphabet_size == 0:
            d = int((i - blank_) / alphabet_size)
            if t < T - d and d > 0:
                print(i, ",", d, '|', t)

257 , 1 | 98
257 , 1 | 97
386 , 2 | 97
257 , 1 | 96
386 , 2 | 96
515 , 3 | 96
257 , 1 | 95
386 , 2 | 95
515 , 3 | 95
644 , 4 | 95
257 , 1 | 94
386 , 2 | 94
515 , 3 | 94
644 , 4 | 94
257 , 1 | 93
386 , 2 | 93
515 , 3 | 93
644 , 4 | 93
257 , 1 | 92
386 , 2 | 92
515 , 3 | 92
644 , 4 | 92
257 , 1 | 91
386 , 2 | 91
515 , 3 | 91
644 , 4 | 91
257 , 1 | 90
386 , 2 | 90
515 , 3 | 90
644 , 4 | 90
257 , 1 | 89
386 , 2 | 89
515 , 3 | 89
644 , 4 | 89
257 , 1 | 88
386 , 2 | 88
515 , 3 | 88
644 , 4 | 88
257 , 1 | 87
386 , 2 | 87
515 , 3 | 87
644 , 4 | 87
257 , 1 | 86
386 , 2 | 86
515 , 3 | 86
644 , 4 | 86
257 , 1 | 85
386 , 2 | 85
515 , 3 | 85
644 , 4 | 85
257 , 1 | 84
386 , 2 | 84
515 , 3 | 84
644 , 4 | 84
257 , 1 | 83
386 , 2 | 83
515 , 3 | 83
644 , 4 | 83
257 , 1 | 82
386 , 2 | 82
515 , 3 | 82
644 , 4 | 82
257 , 1 | 81
386 , 2 | 81
515 , 3 | 81
644 , 4 | 81
257 , 1 | 80
386 , 2 | 80
515 , 3 | 80
644 , 4 | 80
257 , 1 | 79
386 , 2 | 79
515 , 3 | 79
644 , 4 | 79
257 , 1 | 78
386 , 2 | 78
515 , 3 | 78

In [17]:
T = 100
for t in range(T, 0, -1):
    for i in range(645):
        if (i - 30) % alphabet_size == 0:
            d = int(((i - 30) / alphabet_size))
            if t + d < T:
                print(i, ',', d, '|', t)

30 , 0 | 99
30 , 0 | 98
159 , 1 | 98
30 , 0 | 97
159 , 1 | 97
288 , 2 | 97
30 , 0 | 96
159 , 1 | 96
288 , 2 | 96
417 , 3 | 96
30 , 0 | 95
159 , 1 | 95
288 , 2 | 95
417 , 3 | 95
546 , 4 | 95
30 , 0 | 94
159 , 1 | 94
288 , 2 | 94
417 , 3 | 94
546 , 4 | 94
30 , 0 | 93
159 , 1 | 93
288 , 2 | 93
417 , 3 | 93
546 , 4 | 93
30 , 0 | 92
159 , 1 | 92
288 , 2 | 92
417 , 3 | 92
546 , 4 | 92
30 , 0 | 91
159 , 1 | 91
288 , 2 | 91
417 , 3 | 91
546 , 4 | 91
30 , 0 | 90
159 , 1 | 90
288 , 2 | 90
417 , 3 | 90
546 , 4 | 90
30 , 0 | 89
159 , 1 | 89
288 , 2 | 89
417 , 3 | 89
546 , 4 | 89
30 , 0 | 88
159 , 1 | 88
288 , 2 | 88
417 , 3 | 88
546 , 4 | 88
30 , 0 | 87
159 , 1 | 87
288 , 2 | 87
417 , 3 | 87
546 , 4 | 87
30 , 0 | 86
159 , 1 | 86
288 , 2 | 86
417 , 3 | 86
546 , 4 | 86
30 , 0 | 85
159 , 1 | 85
288 , 2 | 85
417 , 3 | 85
546 , 4 | 85
30 , 0 | 84
159 , 1 | 84
288 , 2 | 84
417 , 3 | 84
546 , 4 | 84
30 , 0 | 83
159 , 1 | 83
288 , 2 | 83
417 , 3 | 83
546 , 4 | 83
30 , 0 | 82
159 , 1 | 82
288 , 2 | 82
417 

In [7]:
import torch

k = 129 + 128
k = 129 * 2 + 30


k % 129
k // 129

2

In [2]:
import torch

logits = torch.rand(1,1,1,645)

vocab_size = int(logits.size(-1) / 5)

print(0 % vocab_size)
print(0 // vocab_size)

0
0


In [28]:
import torch

a = torch.rand(2,3,10)

# slice along the last dimension
# 0:5 and then 6:8
print(a)
b = a[:,:,0:5]
c = a[:,:,6:8]
d = torch.cat((b,c),dim=2)
print(d)
print(d.shape)


tensor([[[0.9478, 0.2956, 0.7243, 0.2026, 0.5468, 0.2604, 0.6762, 0.7165,
          0.3339, 0.4041],
         [0.5314, 0.9426, 0.9291, 0.4273, 0.2631, 0.1555, 0.5181, 0.9407,
          0.6747, 0.5361],
         [0.9382, 0.0382, 0.9933, 0.8782, 0.1716, 0.6650, 0.5750, 0.9151,
          0.0885, 0.8244]],

        [[0.8958, 0.7509, 0.9545, 0.1339, 0.4433, 0.5041, 0.4751, 0.1771,
          0.7763, 0.1687],
         [0.2956, 0.7466, 0.9005, 0.1303, 0.0523, 0.4735, 0.1781, 0.8803,
          0.2885, 0.8945],
         [0.2122, 0.5114, 0.3125, 0.7968, 0.9069, 0.8457, 0.0619, 0.0492,
          0.7205, 0.5025]]])
tensor([[[0.9478, 0.2956, 0.7243, 0.2026, 0.5468, 0.6762, 0.7165],
         [0.5314, 0.9426, 0.9291, 0.4273, 0.2631, 0.5181, 0.9407],
         [0.9382, 0.0382, 0.9933, 0.8782, 0.1716, 0.5750, 0.9151]],

        [[0.8958, 0.7509, 0.9545, 0.1339, 0.4433, 0.4751, 0.1771],
         [0.2956, 0.7466, 0.9005, 0.1303, 0.0523, 0.1781, 0.8803],
         [0.2122, 0.5114, 0.3125, 0.7968, 0.9069, 0.0

In [30]:
import torch

a = torch.rand(2,3,4)
b = a.view([-1])
print(a)
print(b)
print(b.shape)

c = b.reshape(2,3,4)
print(c)

tensor([[[0.7830, 0.5265, 0.4255, 0.9633],
         [0.5403, 0.3859, 0.5924, 0.8336],
         [0.9890, 0.0669, 0.5252, 0.1613]],

        [[0.7374, 0.3711, 0.6594, 0.6542],
         [0.6060, 0.2475, 0.3958, 0.0315],
         [0.8193, 0.6480, 0.5936, 0.8579]]])
tensor([0.7830, 0.5265, 0.4255, 0.9633, 0.5403, 0.3859, 0.5924, 0.8336, 0.9890,
        0.0669, 0.5252, 0.1613, 0.7374, 0.3711, 0.6594, 0.6542, 0.6060, 0.2475,
        0.3958, 0.0315, 0.8193, 0.6480, 0.5936, 0.8579])
torch.Size([24])
tensor([[[0.7830, 0.5265, 0.4255, 0.9633],
         [0.5403, 0.3859, 0.5924, 0.8336],
         [0.9890, 0.0669, 0.5252, 0.1613]],

        [[0.7374, 0.3711, 0.6594, 0.6542],
         [0.6060, 0.2475, 0.3958, 0.0315],
         [0.8193, 0.6480, 0.5936, 0.8579]]])


In [32]:
durations = [0,1,2,3,4]

alphabet_size = 129

(durations[1] + 1) * alphabet_size - 1
129 + 128


257

In [54]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '6,7'


import torch

a = torch.load('/home/jykang/NeMo/nemo_experiments/Conformer-TDT-BPE-Stateless-DEP/test3/2023-08-10_14-04-33--val_wer=0.0383-epoch=150-last_expanded.ckpt')
print(a.keys())
print(len(a['state_dict'].keys()))
print(a['optimizer_states'][0].keys())

print(a['optimizer_states'][0]['state'][605]['exp_avg_sq'].shape)
print(a['optimizer_states'][0]['state'][605]['exp_avg'].shape)

print(a['optimizer_states'][0]['state'][604]['exp_avg_sq'].shape)
print(a['optimizer_states'][0]['state'][604]['exp_avg'].shape)


dict_keys(['epoch', 'global_step', 'pytorch-lightning_version', 'state_dict', 'loops', 'callbacks', 'optimizer_states', 'lr_schedulers', 'hparams_name', 'hyper_parameters', 'hparams_type'])
656
dict_keys(['state', 'param_groups'])
torch.Size([134])
torch.Size([134])
torch.Size([134, 320])
torch.Size([134, 320])


In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '6,7'


import torch

checkpoint = torch.load('/home/jykang/NeMo/nemo_experiments/Conformer-TDT-BPE-Stateless-DEP/test3/2023-08-10_14-04-33--val_wer=0.0383-epoch=150-last.ckpt')
state_dict = checkpoint['state_dict']
num_durations = 5

checkpoint['optimizer_states'][0]['state'][605]['exp_avg_sq'] = torch.zeros(645)
checkpoint['optimizer_states'][0]['state'][605]['exp_avg'] = torch.zeros(645)
checkpoint['optimizer_states'][0]['state'][604]['exp_avg_sq'] = torch.zeros(645, 320)
checkpoint['optimizer_states'][0]['state'][604]['exp_avg'] = torch.zeros(645, 320)


label_state = state_dict['joint.joint_net.2.weight'][:-num_durations, :] # (129, 320)
label_bais_state = state_dict['joint.joint_net.2.bias'][:-num_durations] # (129)

duration_state = state_dict['joint.joint_net.2.weight'][-num_durations:, :] # (5, 320)
duration_bais_state = state_dict['joint.joint_net.2.bias'][-num_durations:] # (5)

duration_state = duration_state.repeat_interleave(label_state.shape[0], dim=0) # (645, 320)
duration_bais_state = duration_bais_state.repeat_interleave(label_state.shape[0]) # (645)

label_state = label_state.repeat(num_durations, 1) # (645, 320)
label_bais_state = label_bais_state.repeat(num_durations) # (645)


new_state = label_state + duration_state # (645, 320)
new_bais_state = label_bais_state + duration_bais_state # (645)


new_state_dict = {}
for key in state_dict.keys():
    if key == 'joint.joint_net.2.weight':
        new_state_dict[key] = new_state
    elif key == 'joint.joint_net.2.bias':
        new_state_dict[key] = new_bais_state
    else:
        new_state_dict[key] = state_dict[key]


checkpoint['state_dict'] = new_state_dict
torch.save(checkpoint, '/home/jykang/NeMo/nemo_experiments/Conformer-TDT-BPE-Stateless-DEP/test3/2023-08-10_14-04-33--val_wer=0.0383-epoch=150-last_test2.ckpt')


In [ ]:
print(label_bais_state.shape)
print(label_bais_state[0] == label_bais_state[129])
print(label_bais_state[0] == label_bais_state[1])
print(label_state.shape)
print(label_state[0] == label_state[129])
print(label_state[0] == label_state[1])

In [ ]:
print(duration_bais_state.shape)
print(duration_bais_state[0] == duration_bais_state[129])
print(duration_bais_state[0] == duration_bais_state[1])
print(duration_state.shape)
print(duration_state[0] == duration_state[129])
print(duration_state[0] == duration_state[1])

In [39]:
expanded = torch.load('/home/jykang/NeMo/nemo_experiments/Conformer-TDT-BPE-Stateless-DEP/test3/2023-08-10_14-04-33--val_wer=0.0383-epoch=150-last_expanded.ckpt')


print(expanded['state_dict']['joint.joint_net.2.weight'].shape)
print(expanded['state_dict']['joint.joint_net.2.bias'].shape)   

torch.Size([645, 320])
torch.Size([645])


In [41]:
int((129-30)/129)

0