In [18]:
import torch

# 주어진 텐서
original_tensor = torch.eye(4)
print(original_tensor) 

# 각 row 사이에 제로(row of zeros) 행을 추가할 위치 계산
num_rows, num_cols = original_tensor.size()
expanded_size = 2 * num_rows  # 추가된 제로(row of zeros) 행을 포함한 확장된 크기

# 각 row 사이에 제로(row of zeros) 행 추가
expanded_tensor = torch.zeros(expanded_size, num_rows)
a = torch.zeros(expanded_size, num_rows)
for i in range(num_rows):
    expanded_tensor[i * 2, :] = original_tensor[i, :]
    a[i*2 + 1, :] = original_tensor[i, :]

final = torch.cat((expanded_tensor, a), dim=1)

print(final)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])


In [51]:
mask = torch.ones_like(final, dtype=torch.bool)

print(mask)

src_idx = torch.tensor([1, 3])

mask[src_idx * 2, :] = False
mask[:, src_idx] = False

print(mask)

tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])
tensor([[ True, False,  True, False,  True,  True,  True,  True],
        [ True, False,  True, False,  True,  True,  True,  True],
        [False, False, False, False, False, False, False, False],
        [ True, False,  True, False,  True,  True,  True,  True],
        [ True, False,  True, False,  True,  True,  True,  True],
        [ True, False,  True, False,  True,  True,  True,  True],
        [False, False, False, False, False, False, False, False],
        [ True, False,  True, False,  True,  True,  True,  True]])


In [52]:
tr = final[mask].reshape(-1, 6)

print(tr)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])


In [53]:
unmerged = torch.tensor([[0.],[4.],[1.],[3.],[5.],[7.]])
print(unmerged.shape)

torch.matmul(tr, unmerged)

torch.Size([6, 1])


tensor([[0.],
        [1.],
        [3.],
        [4.],
        [5.],
        [7.]])